#工作名字
name: XMU AutoSignIn

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: 01 15 * * *

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install config
      run: |
        python -m pip install --upgrade pip
        if [ -f config.txt ]; then pip install -r config.txt; fi
    - name: SignIn
      run: |
        sudo cp -p ./chromedriver /usr/bin
        chmod -R 777 /usr/bin/chromedriver
        python ./main.py
      #env:
        #STUID: ${{ secrets.STUID }}
        #PW: ${{ secrets.PW }}
        #SERVER: ${{ secrets.SERVER }}
        #SCKEY: ${{ secrets.SCKEY }}
        #MAIL_NOTICE: ${{ secrets.MAI_NOTICE }}
        #MAILBOX: ${{ secrets.MAILBOX }}
